Container/publiApp/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views
from .views import  ClientesListView\
                    ,ClientesUpdateView\
                    ,ContratoListView\
                    ,Contrato_Create\
                    ,contrato_update\
                    ,PagosListView\
                    ,pagos_create\
                    ,pagos_update\
                    ,video_list\
                    ,ClientesCreate\
                    ,Cliente_Update\
                    ,index\
                    ,busca_cliente\
                    ,pagos_delete\
                    ,get_active_sessions\
                    #,finalizar_sesion\

app_name = "publicidad"

urlpatterns = [
    path('clientes/',login_required(ClientesListView.as_view()), name="clientes_all"),
    path('cliente_create/',ClientesCreate.as_view(), name="cliente_create"),
    path('cliente_update/<int:pk>',Cliente_Update, name="cliente_update"),
    path('contrato/',ContratoListView.as_view(), name="contratos_list"),
    path('contrato_create/',Contrato_Create, name="contrato_create"),
    path('contrato_update/<int:pk>',contrato_update, name="contrato_update"),
    path('pagos/',PagosListView.as_view(), name="pagos_list"),
    path('pagos_create/',pagos_create, name="pagos_create"),
    path('pagos_update/<int:pk>',pagos_update, name="pagos_update"),
    path('pagos_delete/<int:pk>',pagos_delete, name="pagos_delete"),
    path('videos',video_list, name="videos"),
    path('index',index.as_view(), name="index"),
    path('busca_cliente/', busca_cliente, name='busca_cliente'),
    path('sesiones/', get_active_sessions, name='sesiones_activas'),
    #path('sesiones/finalizar_sesion/<int:user_id>/', finalizar_sesion, name='finalizar_sesion'),
]

Container/publicidad/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import LandingPage, Publicidad, CustomLoginView
from . import views
from django.contrib.auth import views as auth_views
from .views import heartbeat

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name='Landing_page'),
    path('publicidad',Publicidad.as_view(),name='publicidad'),
    path('publicidad/', include('publiApp.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('loginview/',CustomLoginView.as_view(),name='loginview'),
    path('api/heartbeat/', heartbeat, name='heartbeat'),
]


Container/templates/base_template.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!--
    <script src="https://code.jquery.com/jquery-3.7.0.js"
        integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous">
    </script>
    -->
    <title>Publicidad</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="icon" href="{% static 'media/publicidad.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-primary" data-bs-theme="dark">
        <div class="container">
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'Landing_page' %}" aria-current="page">Home<span class="visually-hidden">(current)</span></a>
                        </li>
                        {% if connection_count <= user.contrato.dispositivos  %}
                            {% if not user.contrato.debe %}
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'publicidad' %}" id="fullscreen-button">Publicidad</a>
                                </li>
                            {% endif %}
                        {% endif %}
                        {% if request.user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'publicidad:clientes_all' %}">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'publicidad:contratos_list' %}">Contratos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'publicidad:pagos_list' %}">Pagos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'publicidad:sesiones_activas' %}">Sesiones Activas</a>
                        </li>
                        {% endif %}
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                    
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">                      
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="nav-link" style="border:none; background: none; ">SALIR</button>
                            </form>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link" href="">{{ user.nombre | upper }}, Bienvenido</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'loginview' %}">INGRESAR</a>
                        </li>
                    {% endif %}
                </ul>
                {% if request.user.is_authenticated %}
                    {% if request.user.is_staff %}
                    <form class="d-flex my-2 my-lg-0">
                        <input class="form-control me-sm-2" id="busca" type="text" placeholder="Busca" />
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" > Busca  </button>
                    </form>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </nav>

    <main id="fondo">
        <center class="">
            {% block content%} {% endblock %}
        </center>
        <img src="{% static 'media/publicidad.jpg' %}" alt=""
        class="img-fluid rounded-top mx-auto" style="max-width: 40%;" >
    </main>
    
    <footer>
        <div class="bg-body-secondary text-center pt-4 pb-4">
            <h3>SSCOM INFORMATICA</h3>
            <div class="redes">
                    <a>@2024 Manuel Saquilán</a>
                    <a id="email" class="p-2" href="mailto:sscom.desarrollos@gmail.com"><img src="{% static '/media/email.svg' %}" alt="" style="height:25px;color:blue"></a>
                    <a id="whats" class="p-2" href="https://api.whatsapp.com/send/?phone=5493832412280"><img src="{% static '/media/whatsapp.svg' %}" alt="" style="height:25px;"></a>
            </div>
        </div>
    </footer>
    <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
    <script>
        // Obtener el token CSRF desde la cookie
        function getCSRFToken() {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Verifica si el nombre de la cookie es "csrftoken"
                    if (cookie.substring(0, 10) === 'csrftoken=') {
                        cookieValue = decodeURIComponent(cookie.substring(10));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        // Enviar "heartbeat" al servidor cada 60 segundos
        setInterval(function() {
            fetch('/api/heartbeat/', {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'X-CSRFToken': getCSRFToken()  // Incluir el token CSRF en los encabezados
                }
            })
            .then(response => {
                if (!response.ok) {
                    console.error('Error al enviar heartbeat:', response.statusText);
                }
            })
            .catch(error => {
                console.error('Error al enviar heartbeat:', error);
            });
        }, 60000); // 60,000 ms = 60 segundos
    </script>
</body>

</html>