Container/publiApp/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from . import views
from .views import  ClientesListView\
                    ,ClientesUpdateView\
                    ,ContratoListView\
                    ,Contrato_Create\
                    ,contrato_update\
                    ,PagosListView\
                    ,pagos_create\
                    ,pagos_update\
                    ,video_list\
                    ,ClientesCreate\
                    ,Cliente_Update\
                    ,index\
                    ,busca_cliente\
                    ,pagos_delete\
                    ,get_active_sessions\
                    #,finalizar_sesion\

app_name = "publicidad"

urlpatterns = [
    path('clientes/',login_required(ClientesListView.as_view()), name="clientes_all"),
    path('cliente_create/',ClientesCreate.as_view(), name="cliente_create"),
    path('cliente_update/<int:pk>',Cliente_Update, name="cliente_update"),
    path('contrato/',ContratoListView.as_view(), name="contratos_list"),
    path('contrato_create/',Contrato_Create, name="contrato_create"),
    path('contrato_update/<int:pk>',contrato_update, name="contrato_update"),
    path('pagos/',PagosListView.as_view(), name="pagos_list"),
    path('pagos_create/',pagos_create, name="pagos_create"),
    path('pagos_update/<int:pk>',pagos_update, name="pagos_update"),
    path('pagos_delete/<int:pk>',pagos_delete, name="pagos_delete"),
    path('videos',video_list, name="videos"),
    path('index',index.as_view(), name="index"),
    path('busca_cliente/', busca_cliente, name='busca_cliente'),
    path('sesiones/', get_active_sessions, name='sesiones_activas'),
    #path('sesiones/finalizar_sesion/<int:user_id>/', finalizar_sesion, name='finalizar_sesion'),
]

Container/publicidad/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls import include

from .views import LandingPage, Publicidad, CustomLoginView
from . import views
from django.contrib.auth import views as auth_views
from .views import heartbeat

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',LandingPage.as_view(),name='Landing_page'),
    path('publicidad',Publicidad.as_view(),name='publicidad'),
    path('publicidad/', include('publiApp.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('loginview/',CustomLoginView.as_view(),name='loginview'),
    path('api/heartbeat/', heartbeat, name='heartbeat'),
]


Container/publiApp/models.py
import datetime
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.dispatch import receiver
from django.contrib.sessions.models import Session
from django.db.models.signals import post_delete

from django.conf import settings
import uuid

class UsuarioManager(BaseUserManager):
    def create_user(self, email, username, nombre, password):
        if not email:
            raise ValueError('El usuario debe tener un email')

        usuario = self.model(
            username = username,
            email=email,
            nombre=nombre,
            password=password,
        )

        usuario.set_password(password)
        usuario.save(using=self._db)
        return usuario

    def create_superuser(self, username, email, nombre, password):
        usuario = self.create_user(
            username=username,
            email=email,
            nombre=nombre,
            password=password,
            )
        usuario.usuario_administrador = True
        usuario.save(using=self._db)
        return usuario
    
    def get_by_natural_key(self, username):
        return self.get(username=username)

class Cliente(AbstractBaseUser):
    id = models.AutoField(primary_key=True)
    username = models.CharField('Nombre de usuario',unique=True, max_length=100)
    nombre = models.CharField(max_length=100,verbose_name='Nombre',null=False,unique=True) # VERBOSE nombre de las filas en superususario #
    email = models.EmailField(max_length=254,verbose_name='Correo electrónico',null=False,unique=True)
    password = models.CharField(max_length=100,verbose_name="Contraseña",null=False)
    video = models.FileField(upload_to='videos/',null=True,blank=True)
    activo = models.BooleanField(verbose_name='Activo',null=True,default=True)
    usuario_administrador = models.BooleanField(default= False)
    connection_count = models.IntegerField(default=0)
    last_activity = models.DateTimeField(default=timezone.now)
    last_ping = models.DateTimeField(default=timezone.now)
    objects = UsuarioManager()

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ['nombre','email','password']

    def __str__(self):
        #fila = "Nombre: "+" - "+ str(self.nombre)+" Mail: "+ str(self.mail)+" - "+" Password "+ str(self.password)+" - "+" Activo: "+ str(self.activo)+" - "+" Deuda: "+ str(self.deuda)
        fila = self.username
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    
    def has_perm(self,perm,ob = None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    
    @property
    def is_staff(self):
        return self.usuario_administrador
    

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'
        db_table = 'clientes'
        ordering = ['nombre']

    

class Pagos(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.ForeignKey(Cliente,on_delete=models.CASCADE,null=False, blank=False)
    fechaPago = models.DateField(null=False)
    fechaVencimiento = models.DateField(null=False)
    saldo = models.PositiveIntegerField(null=False)
    pago = models.PositiveIntegerField(null=False)

    
    def __str__(self):
        fila = "Nombre"+str(self.nombre)+" - "+"Fecha"+str(self.fechaPago)+"Fecha Vencimiento"+str(self.fechaVencimiento)+"Fecha Proximo Vencimiento"+str(self.fechaProxVencimiento)+" - "+"Pago"+str(self.pago)
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]
    
    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'
        db_table = 'pagos'
        ordering = ['id']
    
class Contrato(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.OneToOneField(Cliente,on_delete=models.CASCADE,null=False, blank=False)
    fechaContrato = models.DateField(null=False)
    fechaVencimientoActual = models.DateField(null=False,default=datetime.date.today)
    debe = models.BooleanField(null=True,default=True)
    cuota = models.PositiveIntegerField(null=False)
    dispositivos = models.PositiveSmallIntegerField(null=False, default=3)

    def __str__(self):
        fila = "Nombre"+str(self.nombre)+" - "+"Fecha"+str(self.fechaContrato)+" - "+"Cuota"+str(self.cuota)+" - "+"Dispositivos"+str(self.dispositivos)
        return fila
    
    def get_fields(self):
        return [
            (field.verbose_name, field.value_from_object(self))
            for field in self.__class__._meta.fields[1:]
        ]

    class Meta:
        verbose_name = 'Contrato'
        verbose_name_plural = 'Contratos'
        db_table = 'contrato'
        ordering = ['id']



        
@receiver(post_delete, sender=Session)
def session_deleted(sender, instance, **kwargs):
    # Aquí puedes agregar la lógica que necesitas
    print("La sesión ha sido eliminada")


class CustomSession(models.Model):
    session_key = models.CharField(max_length=32, unique=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    data = models.JSONField(default=dict)  # o un campo de texto si prefieres almacenar datos serializados
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()
    last_activity = models.DateTimeField(default=timezone.now)

    def is_expired(self):
        return timezone.now() > self.expires_at

Container/publiApp/forms.py
from django import forms

from .models import Cliente, Contrato, Pagos
from datetime import timedelta

class ClientesForm(forms.ModelForm):
    """ Formulario de creación de Clientes 
    
    Variables: 

        password1:
        password2:
    
    """

    
    class Meta:
        model = Cliente
        fields = ["username","nombre", "email","video"]

        labels = {"username":"Nombre de Usuario","nombre": "Nombre del Cliente", "email": "Correo Electrónico","video":"video"}

        widgets = {
            "username": forms.TextInput(attrs={'class': 'form-control','style':'width:300px'}),
            "nombre": forms.TextInput(attrs={'class': 'form-control','style':'width:300px'}),
            "email": forms.EmailInput(attrs={'class': 'form-control','style':'width:300px','placeholder':'correo electrónico'}),
            "video": forms.FileInput(attrs={'class': 'form-control','style':'width:200'})
        }

    password1 = forms.CharField(label='contraseña', widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'style':'width:300px',
               'placeholder':'Ingrese su contraseña',
               'id':'password1',
               'required':'required'}))
    password2 = forms.CharField(label='confirma contraseña', widget=forms.PasswordInput(
        attrs={'class': 'form-control',
               'style':'width:300px',
               'placeholder':'Ingrese nuevamente su contraseña',
               'id':'password2',
               'required':'required'}))

    """def __init__(self, *args, **kwargs):
        super(ClientesForm, self).__init__(*args, **kwargs)
        self.fields['password1'] = self.password1
        self.fields['password2'] = self.password2
    """
    def clean_password2(self):
        """" Validacion de contraseña """
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden")
        return password2

    def save(self,commit = True):
        user = super(ClientesForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
"""
class PagosForm(forms.ModelForm):
    class Meta:  # Add the Meta class
        model = Pagos
        fields = ["nombre", "fechaPago", "fechaVencimiento","saldo","pago"]

        labels = {"nombre": "Cliente", "fechaPago": "Fecha de Pago",
                  "fechaVencimiento":"Fecha de Vencimiento","saldo":"A pagar", "pago": "Importe"}

        widgets = {
            "fechaPago": forms.DateInput(attrs={'class': 'form-control','type':'date','style':'width:auto'}),
            "fechaVencimiento": forms.DateInput(attrs={'class': 'form-control','type':'date','style':'width:auto'}),
            "saldo": forms.NumberInput(attrs={'class': 'form-control','style':'width:auto'}),
            "pago": forms.NumberInput(attrs={'class': 'form-control','style':'width:auto'}),
        }

    nombre = forms.ModelChoiceField(queryset=Cliente.objects.filter(usuario_administrador=False), 
                                    widget=forms.Select(attrs={'class': 'form-control','style':'width:auto'}))

    def __init__(self, *args, **kwargs):
        super(PagosForm, self).__init__(*args, **kwargs)
        self.fields['fechaVencimiento'].widget.attrs['value'] = kwargs['initial']['fecha_vencimiento']
        self.fields['saldo'].widget.attrs['value'] = kwargs['initial']['saldo']
        

    def save(self, commit=True):
        pago = super(PagosForm, self).save(commit=False)
        contrato = pago.nombre.contrato  # Obtener la instancia relacionada de Contrato
        contrato.fechaVencimientoActual = pago.fechaVencimiento + timedelta(days=30)
        pago.fechapago = pago.fechaPago
        pago.pago = pago.pago
        contrato.save()  # Guardar la instancia actualizada de Contrato
        pago.save()  # Guardar la instancia de Pago
        return pago
"""    

class ContratoForm(forms.ModelForm):
    class Meta:  # Add the Meta class
        model = Contrato
        fields = ["nombre", "fechaContrato", "fechaVencimientoActual","cuota", "dispositivos"]

        labels = {
            "nombre": "Cliente",
            "fechaContrato": "fecha de Contrato",
            "fechaVencimientoActual": "fecha de Vencimiento",
            "cuota": "Valor de Cuota",
            "dispositivos": "Cantidad de Dispositivos",
        }

        widgets = {
            "fechaContrato": forms.DateInput(attrs={'class': 'form-control','type':'date','style':'width:auto'}),
            "fechaVencimientoActual": forms.DateInput(attrs={'class': 'form-control','type':'date','style':'width:auto'}),
            "cuota": forms.NumberInput(attrs={'class': 'form-control','style':'width:auto'}),
            "dispositivos": forms.NumberInput(attrs={'class': 'form-control','style':'width:auto'}),
        }

    nombre = forms.ModelChoiceField(queryset=Cliente.objects.filter(usuario_administrador=False), 
                                    widget=forms.Select(attrs={'class': 'form-control','style':'width:auto'}))

Container/publiApp/templates/clientes_form.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Nuevo Cliente</H1>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'publicidad:clientes_all' %}" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Aceptar</button>
        </form>
    </div>
{% endblock %}

Container/publiApp/templates/clientes_update.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    
    <div class="container">
        <H1>{{ Titulo }}</H1>
        <form action="{{ cliente.id }}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!--<div>{{form.as_p}}-->    
                <label for="id_nombre">Cliente:</label>
                <input type="text" name="nombre" maxlength="30" required="True" id="id_nombre"
                    value="{{ cliente.nombre }}" class="form-control" style="width: 400px;" />
            
                <label for="id_mail">Mail:</label>
                <input type="email" name="email" id="id_mail" value="{{ cliente.email }}"
                    class="form-control" style="width: 400px;" />
            
                <label for="id_activo">Activo:</label>
                <select name="activo" id="id_activo" class="form-control" style="width: auto;">
                    {% if cliente.activo %}
                    <option value="True" selected >SI</option>
                    <option value="False" >NO</option>
                    {% else %}
                    <option value="True" >SI</option>
                    <option value="False" selected >NO</option>
                    {% endif %}
                </select>
                <label for="">Video</label>
                <input type="file" name="video" id="id_video" class="form-control" value="{{ cliente.video }}"/>
                <div class="label-input m-4">
                    <a href="{% url 'publicidad:clientes_all' %}" class="btn btn-danger">Cancelar</a>
                    <input type="submit" value="{{ tipo }}" class="btn btn-success" />
                </div>
        </form>
    </div>
{% endblock %}

Container/publiApp/templates/clientes_view.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Clientes</H1>
    <a class="btn btn-info m-4" href="{% url 'publicidad:cliente_create' %}">Nuevo Cliente</a>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Mail</th>
                        <th scope="col">Activo</th>
                        <th scope="col">Video</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% if clientes %}
                    {% for cliente in clientes %}
                        {% if not cliente.usuario_administrador %}
                        <tbody>
                            <tr class="">
                                <td scope="row">{{ cliente.nombre}}</td>
                                <td>{{ cliente.email }}</td>
                                {% if cliente.activo %}
                                    <td>SI</td>
                                {% else %}
                                    <td>NO</td>
                                {% endif %}
                                <td><video width="200" height="150" controls>
                                    {% if cliente.video %}
                                    <source src="{{ cliente.video.url }}" type="video/mp4">
                                    Tu navegador no soporta video HTML5
                                    {% endif %}
                                </video></td>
                                <td><a class="btn btn-warning" href="#}">Cambia Password</a></td>
                                <td><a class="btn btn-primary" href="{% url 'publicidad:cliente_update' cliente.id %}">Editar</a></td>
                            </tr>
                        </tbody>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </table>
        </div>
        
    </div>
{% endblock %}

Container/publiApp/templates/contrato_form.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Nuevo Contrato</H1>
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <a href="{% url 'publicidad:contratos_list' %}" class="btn btn-danger">Cancelar</a>
            <button type="submit" class="btn btn-success">Aceptar</button>
        </form>
    </div>
{% endblock %}

Container/publiApp/templates/contrato_update.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    
    <div class="container">
        <H1>{{ Titulo }}</H1>
        <form action="{{ contrato.id }}" method="post">
            {% csrf_token %}
            <!--{{form.as_p}}-->
            <label>Nombre:</label>
                <input type="text" name="nombre" value="{{ contrato.nombre }}"
                    class="form-control text-center" style="width: auto;color: grey;" disabled/>
            
                <label>Fecha de Contrato:</label>
                <input type="datetime" name="fechaContrato" value='{{ contrato.fechaContrato | date:"Y-m-d" }}'
                    class="form-control  text-center" style="width: auto;color: grey;"  disabled/>

                <label>Fecha de Vencimiento Actual:</label>
                <input type="date" name="fechaVencimientoActual" value='{{ contrato.fechaVencimientoActual | date:"Y-m-d" }}'
                    class="form-control text-center" style="width: auto;" />

                <label>Registra Deuda:</label>
                <select name="debe" id="id_debe" class="form-control" style="width: auto;">
                    {% if contrato.debe %}
                    <option value="True" selected >SI</option>
                    <option value="False" >NO</option>
                    {% else %}
                    <option value="True" >SI</option>
                    <option value="False" selected >NO</option>
                    {% endif %}
                </select>

                <label>cuota:</label>
                <input type="number" name="cuota" value="{{ contrato.cuota }}"
                    class="form-control text-center" style="width: auto;" min="0"/>
            
                <label>Dispositivos:</label>
                <input type="number" name="dispositivos" value="{{ contrato.dispositivos }}"
                    class="form-control text-center" style="width: auto;" min="1"/>
                
            <div class="label-input m-4">
                <a href="{% url 'publicidad:contratos_list' %}" class="btn btn-danger">Cancelar</a>
                <input type="submit" value="{{ tipo }}" class="btn btn-success" />
            </div>
        </form>
    </div>
    {% endblock %}

Container/publiApp/templates/contrato_view.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Contrato</H1>
    <a class="btn btn-info m-3" href="{% url 'publicidad:contrato_create' %}">Nuevo Contrato</a>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Fecha de Contrato</th>
                        <th scope="col">Fecha de Vencimiento</th>
                        <th scope="col">Registra Deuda</th>
                        <th scope="col">Cuota</th>
                        <th scope="col">Dispositivos</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for contrato in contratos %}
                <tbody>
                    <tr class="">
                        <td scope="row">{{ contrato.nombre.nombre }}</td>
                        <td>{{ contrato.fechaContrato }}</td>
                        <td>{{ contrato.fechaVencimientoActual }}</td>
                        {% if contrato.debe %}
                            <td>SI</td>
                        {% else %}
                            <td>NO</td>
                        {% endif %}
                        <td>$ {{ contrato.cuota }}</td>
                        <td>{{ contrato.dispositivos }}</td>
                        <td><a class="btn btn-primary" href="{% url 'publicidad:contrato_update' contrato.id %}">Editar</a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        
    </div>
{% endblock %}

Container/publiApp/templates/pagos_create.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Nuevo Pago</H1>
    <div class="container">
        <form action="{% url 'publicidad:busca_cliente' %}" name="busca" id="busca" method="post">
            {% csrf_token %}
            <label>Seleccione el Cliente:</label>
            <input type="text" name="nombrebuscado" list=buscar
                class="form-control" style="width: auto"/>
            <datalist id="buscar">
                {% for cliente in clientes %}
                    {% if not cliente.usuario_administrador %}
                        <option value="{{ cliente.nombre }}">{{ cliente.nombre }}</option>
                    {% endif %}
                {% endfor %}
            </datalist>
            <div class="label-input m-3">
                <button type="submit" class="btn btn-primary">Busca</button>
            </div>  
        </form>
        <form action="{% url 'publicidad:pagos_create' %}" name="crea" method="post">
            {% csrf_token %}
            <!--{{ form.as_p }}-->
            <label>Cliente:</label>
            <input type="text" name="id" value='{{ id }}''
                class="form-control text-center" style="width: auto" hidden readonly/>
            <input type="text" name="nombre" value='{{ cliente }}''
                class="form-control text-center" style="width: auto" readonly/>
            <label>Fecha de Vencimiento:</label>
            <input type="datetime" name="fechaVencimiento" value='{{ vencimiento | date:"Y-m-d" }}'
                class="form-control text-center" style="width: auto;" readonly/>
            <label>A pagar:</label>
            <input type="number" name="saldo" value="{{ saldo }}"
                class="form-control text-center" style="width: auto;" min="0" readonly/>   
            <label>Fecha de Pago:</label>
            <input type="date" name="fechaPago"
                class="form-control text-center" style="width: auto;" />
            <label>Importe:</label>
            <input type="number" name="pago" value="{{ saldo }}"
                class="form-control text-center" style="width: auto;" min="0"/>    
            <div class="label-input m-3">
                <a href="{% url 'publicidad:pagos_list' %}" class="btn btn-danger">Cancelar</a>
                <button type="submit" class="btn btn-success">Aceptar</button>
            </div>     
        </form>
    </div>
    
    
{% endblock %}

Container/publiApp/templates/pagos_update.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    
    <div class="container">
        <H1>{{ Titulo }}</H1>
        <form action="{{ pagos.id }}" method="post">
            {% csrf_token %}
            <!--<div>{{form.as_p}}-->    
                <label>Comercio:</label>
                <input type="text" name="nombre" value="{{ pagos.nombre }}"
                    class="form-control" style="width: auto;color: grey;" readonly/>
            
                <label>Fecha de Pago:</label>
                <input type="datetime" name="fechaPago" value='{{ pagos.fechaPago | date:"d/m/Y" }}'
                    class="form-control" style="width: auto;" />
            
                <label>Importe:</label>
                <input type="number" name="pago" value="{{ pagos.pago }}"
                    class="form-control" style="width: auto;" min="0"/>         
                <div class="label-input">
                    <input type="submit" value="{{ tipo }}" class="btn btn-success" />
                </div>
        </form>
    </div>
{% endblock %}

Container/publiApp/templates/pagos_view.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <H1>Pagos</H1>
    <a class="btn btn-info m-3" href="{% url 'publicidad:pagos_create' %}">Nuevo Pago</a>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th scope="col">Nombre</th>
                        <th scope="col">Fecha de Vencimiento</th>
                        <th scope="col">A pagar</th>
                        <th scope="col">Fecha de pago</th>
                        <th scope="col">Importe</th>
                        <th scope="col"></th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                {% for pago in pagos %}
                <tbody>
                    <tr class="">
                        <td scope="row">{{ pago.nombre.nombre}}</td>
                        <td>{{ pago.fechaVencimiento }}</td>
                        <td>{{ pago.saldo }}</td>
                        <td>{{ pago.fechaPago }}</td>
                        <td>{{ pago.pago }}</td>
                        <td><a class="btn btn-danger" href="{% url 'publicidad:pagos_delete' pago.id %}">Eliminar</a></td>
                        <td><a class="btn btn-primary" href="{% url 'publicidad:pagos_update' pago.id %}">Editar</a></td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        
    </div>
{% endblock %}

Container/publiApp/templates/sesiones_activas.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <h1>Sesiones Abiertas</h1>
    <div class="container">
        <div class="table-responsive">
            <table class="table table-primary">
                <thead>
                    <tr>
                        <th class="text-center" scope="col">Nombre</th>
                        <th class="text-center" scope="col">Dispositivos Contratados</th>
                        <th class="text-center" scope="col">Cookie sesion key</th>
                        <th class="text-center" scope="col">Expiración de Sesión</th>
                        <th class="text-center" scope="col">Última Actividad</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                        <!--{% if not user.is_staff %}-->
                                {% for session in active_sessions %}
                                    {% if session.user_id == user.id %}
                                        
                                            <tr>
                                                <td class="text-center">{{ user.nombre }}</td>
                                                <td class="text-center">{{ user.contrato.dispositivos }}</td>    
                                                
                                                <td class="text-center">{{ session.session_key }}</td>
                                                <td class="text-center">{{ session.expires_at }}</td>
                                                <td class="text-center">{{ session.last_activity }}</td>
                                            </tr>
                                        
                                    {% endif %}
                                {% endfor %}
                            
                        <!--{% endif %}-->
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

Container/publiApp/templates/video_list.html
{% extends "base_template.html" %}
{% load static %}

{% block content %}
    <video id="video-player" width="100%" controls autoplay>
        <source id="video-source" src="" type="video/mp4">
    </video>
    <script>
        var videos = [{% for video in videos %}"{{ video.video.url }}"{% if not forloop.last %},{% endif %}{% endfor %}];
        var currentVideo = 0;
        console.log(videos);
        
        
        function playNextVideo() {
            var videoPlayer = document.getElementById('video-player');
            var videoSource = document.getElementById('video-source');

            videoSource.src = videos[currentVideo];
            
            videoPlayer.load();
            videoPlayer.play();
       
            videoPlayer.addEventListener('ended', function() {
                currentVideo = currentVideo + 1;
                if (currentVideo === videos.length) {
                    currentVideo = 0;
                    
                }
                playNextVideo();
            });
            
        }

        
        playNextVideo();

        
        
    </script>
{% endblock %}